application:
  address: '0.0.0.0'
  port: 0
  hash_secret: 'hash_secret'
  jwt_secret: 'jwt_secret'
database:
  user: 'user'
  password: 'password'
  host: 'localhost'
  port: '5432'
  db_name: 'postgres'
